### ISSUE TITLE
Skeletons response adds the last block identifier farther than expected 

### ISSUE THREAD

**Issue by lsebrie** [rsksmart/rskj#1002]
While reviewing code of pr #1001 we found that the skeleton response message generated on NodeBlockProcessor has the last block identifier with a bigger number than it should.
This behavior can be reproduced on #1001 with the failed tests:

stopSyncingAfter5SkeletonChunks
syncInMultipleStepsWithLongBlockchain

**Comment by joaquinlpereyra-iov** [comment]
Is it reasonable to expect this issue to be fixed on a couple of days? We _really_ want to merge #1001 on time for the next release.

**Comment by joaquinlpereyra-iov** [comment]
Fix was marged so I'm closing this.
