### ISSUE TITLE
Different behavior between mutableTrie and mutableTrieCache

### ISSUE THREAD

**Issue by julianlen** [rsksmart/rskj#1026]
The next [test](https://github.com/rsksmart/rskj/blob/7fc7c7eff2393db87b6c81d331a67afe6d33d20d/rskj-core/src/test/java/co/rsk/db/MutableTrieCacheTest.java#L435) show this behavior. When an empty value is stored in Mutable trie, the value hash returned is Zero hash. This is because in the [Trie](https://github.com/rsksmart/rskj/blob/cf06f8b58672d26ff57ee42804d0f9fa31e5cf84/rskj-core/src/main/java/co/rsk/trie/Trie.java#L743) class, when **put** method is called with a key and an empty array as value, null is stored. Moreover when **get** method is called with the previous key, null is returned. Then, in **MutableTrieImpl::GetValueHash**, when a trie returns a null value, it is interpreted like the key doesn't exist. 

In the other hand, when in MutableTrieCache is stored a key with an empty array as value, it is stored as it is. So when **get** is called with the previous key, an empty array is returned. Then **MutableTrieCache::GetValueHash**, when a trie returns an empty array as value, it is interpreted as it is, so it returns the hash of an empty array.

**Comment by SergioDemianLerner** [comment]
nice finding
