### ISSUE TITLE
error retrieving chainID from backendURL: 404 Not Found

### ISSUE THREAD

**Issue by Eknir** [rsksmart/rskj#1122]
The current RSK testnet Public node does not support all JSON RPC methods, needed for development. In particular, [Swarm](http://swarm.ethereum.org) can not run on RSK, due to the missing function eth_chainId.

**Comment by Eknir** [comment]
Was already merged https://github.com/rsksmart/rskj/pull/1110

**Comment by saurik** [comment]
```
$ curl -s -X POST --data '{"jsonrpc":"2.0","id":"","method":"eth_chainId","params":[]}' -H 'content-type: application/json' https://public-node.rsk.co/
{"jsonrpc":"2.0","id":"","error":{"code":-32603,"message":"Internal server error"}}
```
