### ISSUE TITLE
Performance Issue in Save Transaction Receipts

### ISSUE THREAD

**Issue by ajlopez** [rsksmart/rskj#1125]
The transaction receipt corresponding to a transaction included into a block, is persisted using `ReceiptStoreImpl`:

```
    @Override
    public void add(byte[] blockHash, int transactionIndex, TransactionReceipt receipt){
        byte[] txHash = receipt.getTransaction().getHash().getBytes();

        TransactionInfo newTxInfo = new TransactionInfo(receipt, blockHash, transactionIndex);

        List<TransactionInfo> txsInfo = getAll(txHash);

        txsInfo.add(newTxInfo);

        List<byte[]> encodedTxs = new ArrayList<>();

        for (TransactionInfo ti : txsInfo) {
            encodedTxs.add(ti.getEncoded());
        }

        byte[][] txsBytes = encodedTxs.toArray(new byte[encodedTxs.size()][]);

        receiptsDS.put(receipt.getTransaction().getHash().getBytes(), RLP.encodeList(txsBytes));
    }
```

The problem is that ALL OTHER RECEIPTS of the same transaction are READ AND WRITTEN again. When this code is executed in a network (like RSK mainnet), where there are MANY competitive blocks with the same transaction, produced by the merge mining procesos, then the number of bytes read and writtten is not linear with the number of transaction receipts produced for the same transaction.

**Comment by aeidelman** [comment]
This has been enhanced in #1459
