### ISSUE TITLE
Transaction queued for ever (until timeout discard) and not relayed in TransactionPool

### ISSUE THREAD

**Issue by ajlopez** [rsksmart/rskj#1130]
This tests (add it to `TransactionPoolImplTest`) fails:

```
    @Test
    public void addTwoTransactionsOutOfOrderInNonceUsingAddTransaction() {
        Coin balance = Coin.valueOf(1000000);
        createTestAccounts(2, balance);

        Transaction tx1 = createSampleTransactionWithGasPrice(1, 0, 1000, 0, 1);
        Transaction tx2 = createSampleTransactionWithGasPrice(1, 0, 2000, 1, 2);

        Assert.assertTrue(transactionPool.addTransaction(tx2).transactionWasAdded());
        Assert.assertTrue(transactionPool.addTransaction(tx1).transactionWasAdded());

        Assert.assertTrue(transactionPool.getPendingTransactions().stream().anyMatch(tx -> tx.getHash().equals(tx2.getHash())));
        Assert.assertTrue(transactionPool.getPendingTransactions().stream().anyMatch(tx -> tx.getHash().equals(tx1.getHash())));
    }
```

because it uses `TransactionPool.addTransaction` directly. I don't know any case to use this method from OUTSIDE. The problem is that the out of order transaction is queued when it is added, but it is NOT removed from queued transactions and added to pending transactions when the missing companion transaction is added.

Compare with this tests that runs OK:

```
    @Test
    public void addTwoTransactionsOutOfOrderInNonceUsingAddTransactions() {
        Coin balance = Coin.valueOf(1000000);
        createTestAccounts(2, balance);

        Transaction tx1 = createSampleTransactionWithGasPrice(1, 0, 1000, 0, 1);
        Transaction tx2 = createSampleTransactionWithGasPrice(1, 0, 2000, 1, 2);

        List<Transaction> txs = new ArrayList<>();

        txs.add(tx2);
        txs.add(tx1);

        transactionPool.addTransactions(txs);

        Assert.assertTrue(transactionPool.getPendingTransactions().stream().anyMatch(tx -> tx.getHash().equals(tx2.getHash())));
        Assert.assertTrue(transactionPool.getPendingTransactions().stream().anyMatch(tx -> tx.getHash().equals(tx1.getHash())));
    }
```

This second test uses `TransactionPoolImpl.addTransactions`. This is the expected method to use to keep the queued and pending transaction state OK.

The method `TransactionPoolImpl.addTransaction` is used externally in few but important points. Notable, from `EthModuleTransactionBase` to process transactions that came from JSON RPC.

So, if you send two transactions, out of order (possible, if you are using, ie, asynchronous scripts in NodeJS), then the transaction with higher nonce IS NEVER RELAYED and processed by the rest of the network,

The above tests are included in https://github.com/ajlopez/rskj/tree/addtxbug

**Comment by fedejinich** [comment]
can we close this issue?

**Comment by pmprete** [comment]
@ajlopez  can we close this issue?
