### ISSUE TITLE
Transaction and Uncles Lists in Block are not Immutable

### ISSUE THREAD

**Issue by ajlopez** [rsksmart/rskj#1158]
This code is from one of the `Block` constructors:

```
        this.transactionsList = Collections.unmodifiableList(transactionsList);
        this.uncleList = Collections.unmodifiableList(uncleList);

```

Altough this code prevents the modification of `this.transactionList` directly, the original list could still be modified externally, affecting the integrity of the block.

To prevent such behavior, maybe a list copy with unmodifiable view could be used.

**Comment by kiminuo** [comment]
@ajlopez Hi, what would https://github.com/rsksmart/rskj/pull/1190?
