### ISSUE TITLE
Configuration Objects Used Directly In Logic

### ISSUE THREAD

**Issue by aeidelman** [rsksmart/rskj#12]
Currently, in many places, the global configuration objects SystemProperties.CONFIG and RskSystemProperties.RSKCONFIG (two instances, there is another issue to unify them). These values are used directly in logic: we cannot inject the needed values for testing purposes. These values are used directly in logic: we cannot inject the needed values for testing purposes. And we cannot create new empty config objects: the empty constructor has logic to retrieve their values from some other place. These two objects are global singletons, and their use should be refactored

**Comment by tinchou** [comment]
Fixed in https://github.com/rsksmart/rskj/pull/415
