### ISSUE TITLE
RSK 2.0.1 does not sync after upgraded from 1.0.3

### ISSUE THREAD

**Issue by lcgogo** [rsksmart/rskj#1237]
RSK 2.0.1 does not sync after upgraded from 1.0.3
After stop 2.0.1 and restart 1.0.3, still no sync blocks.

The log repeats like the attachment.
[rsk.log](https://github.com/rsksmart/rskj/files/4613528/rsk.log)

My conf is like the attachment.
[rskconf.txt](https://github.com/rsksmart/rskj/files/4613541/rskconf.txt)

**Comment by nicops** [comment]
hard to say what is the issue with those logs, only things we see is that you're getting JSON RPC requests
