### ISSUE TITLE
the file size excesed configured limit 2,56 MbCode insight feature are not available

### ISSUE THREAD

**Issue by bilbma** [rsksmart/rskj#1239]
![Captura de pantalla de 2020-05-20 19-28-59](https://user-images.githubusercontent.com/4594919/82478600-716c8080-9ad1-11ea-890f-6d679560b78e.png)
Runing mainnet,but Code insight feature are not available.Who have change it?
How to write proof of work?

nstance: RskJ/1.3.0/Linux/Java1.8/WASABI-c762485
coinbase: 0xec4ddeb4380ad69b3e509baad9f158cdf4e4681d
at block: 492901 (Fri Jun 15 2018 03:37:14 GMT+0200 (CEST))
 modules: debug:1.0 eth:1.0 evm:1.0 net:1.0 personal:1.0 rpc:1.0 rsk:1.0 sco:1.0 trace:1.0 txpool:1.0 web3:1.0

> eth.blockNumber
493004
> net.version
"30"
> eth.blockNumber
493142

**Comment by nicops** [comment]
Those are your IDE issues, not related to RSK itself
