### ISSUE TITLE
Consensus incompatibility with Ethereum

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#1264]
I detected that when a contract is created but the contract has empty code, then EXTCODEHASH for this contract returns all-zeros, when according to the [EIP-1052](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1052.md) :

_The EXTCODEHASH of the account without code is c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 what is the keccack256 hash of empty data._  

The problem is in co/rsk/db/MutableTrieImpl.java:getValueHash() in the line:
```
 if (atrie == null) {
            return Keccak256.ZERO_HASH;
        }
```
It should be:
```
 if (atrie == null) {
            return null;
        }
```
And the method  org/ethereum/db/MutableRepository.java:getCodeHash() should read:
```

@Override
    public synchronized Keccak256 getCodeHash(RskAddress addr) {

        if (!isExist(addr)) {
            return Keccak256.ZERO_HASH;
        }

        if (!isContract(addr)) {
            return new Keccak256(Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY));
        }
 
        byte[] key = trieKeyMapper.getCodeKey(addr);
        Keccak256 tmpValue = mutableTrie.getValueHash(key);
        
       // New code ---->
        if ((isContract(addr)) && (tmpValue==null)) {        
           return new Keccak256(Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY));
        }  
        // <------ End new code
        
       return tmpValue;
    }
```

**Comment by SergioDemianLerner** [comment]
I've checked in BESU code and it complies with the EIP. I've also checked geth codes, and it seems to comply. But I haven't executed a test in Ethereum.

**Comment by SergioDemianLerner** [comment]
Here is a test to check the non-standard behavior in RSK:
```

@Test
    public void testCREATE2_EmptyCodeNonStandard() {
        /**
         * Check for a call with no init_code
         * (Note that it should return same address than previous test)
         */
        callCreate2("0x0f6510583d425cfcf94b99f8b073b44f60d1912b",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "",
                0,
                0,
                "65BD0714DEFB919BC02F9507D6F9D9CD21195ECC",
                32012);

        byte[] emptyHash = Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY);
        Keccak256 existentHash = invoke.getRepository().getCodeHash(new RskAddress("65BD0714DEFB919BC02F9507D6F9D9CD21195ECC"));
        // This is was is currently happening: 
        // Assert.assertArrayEquals(Keccak256.ZERO_HASH.getBytes(), existentHash.getBytes());
        // This is what it should happen:
        Assert.assertArrayEquals(emptyHash, existentHash.getBytes());
    }
```
You can insert this test in co/rsk/vm/Create2Test.java to execute it.

**Comment by SergioDemianLerner** [comment]
I tested it on Remix - Ethereum and it complies with the EIP:
```

pragma solidity >0.4.99 <0.6.11;

contract Factory {

  bytes32 public rhash;
  address public raddr;
  uint public rsize;
    
  constructor() public {
      deploy();
  }
  
  function deploy() public  {
  bytes32 h;
  address addr;
  uint s;
    assembly {
      addr := create2(0, 0x00, 0, 0x00)
      h :=extcodehash(addr)
      s :=extcodesize(addr)
    }

   raddr = addr;
   rhash = h;
   rsize =s;

  }
}
     
```

**Comment by SergioDemianLerner** [comment]
The result is:
raddr: address: 0x0DB6a68e2c7511a4b04B506f4d8A0c05aF239A39
rhash: bytes32: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
rsize: uint256: 0

**Comment by julianlen** [comment]
> I detected that when a contract is created but the contract has empty code, then EXTCODEHASH for this contract returns all-zeros, when according to the [EIP-1052](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1052.md) :
> 
> _The EXTCODEHASH of the account without code is c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 what is the keccack256 hash of empty data._
> 
> The problem is in co/rsk/db/MutableTrieImpl.java:getValueHash() in the line:
> 
> ```
>  if (atrie == null) {
>             return Keccak256.ZERO_HASH;
>         }
> ```
> 
> It should be:
> 
> ```
>  if (atrie == null) {
>             return null;
>         }
> ```
> 
> And the method org/ethereum/db/MutableRepository.java:getCodeHash() should read:
> 
> ```
> 
> @Override
>     public synchronized Keccak256 getCodeHash(RskAddress addr) {
> 
>         if (!isExist(addr)) {
>             return Keccak256.ZERO_HASH;
>         }
> 
>         if (!isContract(addr)) {
>             return new Keccak256(Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY));
>         }
>  
>         byte[] key = trieKeyMapper.getCodeKey(addr);
>         Keccak256 tmpValue = mutableTrie.getValueHash(key);
>         
>        // New code ---->
>         if ((isContract(addr)) && (tmpValue==null)) {        
>            return new Keccak256(Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY));
>         }  
>         // <------ End new code
>         
>        return tmpValue;
>     }
> ```

Recall this, in the last if is not necessary to ask for `isContract`, It knows is a contract because de previous `if(!isContract)`

**Comment by SergioDemianLerner** [comment]
BTW, Keccak256Helper.keccak256(EMPTY_BYTE_ARRAY) should be a static final value. I doesn't make sense to compute it every time.

**Comment by aeidelman** [comment]
@ajlopezrsk can we close this issue?
