### ISSUE TITLE
Correct gas limit gets transaction failed

### ISSUE THREAD

**Issue by pmprete** [rsksmart/rskj#1279]
For some reason this Tx is getting an error even tough it has a valid nonce and gas price. The gas price was obtained using estimateGas
https://explorer.testnet.rsk.co/tx/0x545040a9a595f0c065fb5f2ef08fad9035023c3221f37f651f531689b70b6ad3
Now, the same transaction (you can see is the same data) with a higher gasLimit worked correctly even tough the gas used is lower than the gas limit used in the previous transaction. The gas limit on this transaction was set to 50.000.
https://explorer.testnet.rsk.co/tx/0xb13b72bbcd0232a766e7d193ffaf9a9e5601751befd8d0712502ad87e8999307

This is happening consistently for the withdraw method of the WRBTC contract when withdrawing 0.1 WRBTC
The contract  is https://explorer.testnet.rsk.co/address/0x09b6ca5e4496238a1f176aea6bb607db96c2286e?__ctab=general
you can  check the code in the Code tab of the explorer, or in the repository https://github.com/Think-and-Dev/wrbtc

Here are other failed and successful transactions so you see that this is not a one time thing
Failed:
https://explorer.testnet.rsk.co/tx/0xe1b0c0d2316a006fe7a3a4fe241b6ecbe0d9796570b7873c0eb3483459aa6da7
https://explorer.testnet.rsk.co/tx/0x66e3d1b37b6bd3be55b3c3c05596eca5edb2729fbd7f5aa8720eeebd680a8709
https://explorer.testnet.rsk.co/tx/0xb60dd5ad710732e2b2e21d4a0729c14f8a927b4d95969a3ccf43a7f5aecdbb21
Successful:
https://explorer.testnet.rsk.co/tx/0x588cd3eb9dd5762f720c46510eb99129585f32a08476b5247363731caf81e54a
https://explorer.testnet.rsk.co/tx/0x5b7b14a7fee7abfb5a85a08b143cd6d7b996bea77f91b5b00ad127ed82efdfe5

**Comment by pmprete** [comment]
This issue is originated by https://github.com/rsksmart/rskj/issues/948

**Comment by fedejinich** [comment]
Just to clarify you are getting the OOG because we are not taking into account the pre-send amount required by CALLs with value. 

For example, when you want to [withdraw](https://github.com/Think-and-Dev/wrbtc/blob/5efd1e9c9ccbdd503453a1cedec2e0924c36e94e/contracts/WRBTC.sol#L45) you're also transfering value (aka call with value), which leads to an OOG.

Correct me if i'm wrong (as we are considering to finally fix this)

**Comment by pmprete** [comment]
Hi Fede, this is not only a problem when sending RBTC, i have gas estimation issues with other contracts that do not require to send currency.
I'll try to add another example, but i don't think i'll have it until next week

**Comment by pmprete** [comment]
Another example for this is 
https://explorer.testnet.rsk.co/tx/0xf064b987d7b25541a958b5031dfa5ab3a1486a87c4ea9ac9eea81f8107e12a18
https://explorer.testnet.rsk.co/tx/0x56f937490f34d3c71272601722af193fe8f32f47f04a4d6d6c2ce29444ab4c46
Both are the exact same transaction except that the one that succedded has a higher gas limit. The gas limit given in the one that failed is the same gas that it was used in the transaction that was successful.

The contract that is being called is a minimal proxy https://eips.ethereum.org/EIPS/eip-1167

The underlying function being called is is https://github.com/Think-and-Dev/taringa-nft-contracts/blob/main/contracts/smartwallet/SmartWallet.sol#L69
