### ISSUE TITLE
JSON/RPC eth_getCode returns non-empty code for addresses that don't exist

### ISSUE THREAD

**Issue by saurik** [rsksmart/rskj#1386]
When using eth_getCode on non-existent addresses RSK returns "0x00"--which would mean there is a single zero byte of code--instead of the (correct) empty data value "0x".

```
# curl -L --post301 -s -H 'content-type: application/json' --data '{"id":"","jsonrpc":"2.0","method":"eth_getCode","params":["0x34F0Ed1E696eC6dCe80116f25664aFF45E6D6321", "latest"]}' https://public-node.rsk.co/ | jq
{
  "jsonrpc": "2.0",
  "id": "",
  "result": "0x00"
}
```

**Comment by patogallaiovlabs** [comment]
We are already working on it. :)
https://github.com/rsksmart/rskj/pull/1352

**Comment by saurik** [comment]
@patogallaiovlabs I just want to verify that, while this issue is marked closed, the public endpoint at https://public-node.rsk.co/ does not yet have this fix deployed.
