### ISSUE TITLE
JSON/RPC endpoint returns HTTP status 500 on error (should be 200)

### ISSUE THREAD

**Issue by saurik** [rsksmart/rskj#1387]
When JSON/RPC endpoints return errors, the resulting body JSON document contains the error message and the HTTP status is supposed to be 200. While I personally can see an argument for why JSON/RPC "should have" returned an HTTP error in this case, it actually doesn't make much sense in other contexts and no matter what 500 would be the wrong code to return.

```
# curl -w '%{http_code}\n' -o/dev/null -s -H 'content-type: application/json' --data '{"id":"","jsonrpc":"2.0","method":"eth_chainId","params":[2]}' https://public-node.testnet.rsk.co/
500
```
```
# curl -L --post301 -w '%{http_code}\n' -o/dev/null -s -H 'content-type: application/json' --data '{"id":"","jsonrpc":"2.0","method":"eth_chainId","params":[2]}' https://ethereumclassic.network/
200
```

**Comment by patogallaiovlabs** [comment]
I'll take a look... make sense what you say, the node behaves like v1.0 spec, for v2.0 all the codes shouldn't be necessary. We can follow sthg like this: https://github.com/hyperledger/besu/issues/549

**Comment by bguiz** [comment]
can we get this addressed in the next release pls?
