### ISSUE TITLE
Websocket connection over SSL returns 501 

### ISSUE THREAD

**Issue by 1doce8** [rsksmart/rskj#1446]
Hi,

Connection to localhost like this established successfully 

>  curl --include --no-buffer --header "Connection: Upgrade"  --header "Upgrade: websocket" http://localhost:4445/websocket

External connection also works great

> curl --include  --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Host: MY_DOMAIN" http://MY_PUBLIC_IP:4445/websocket

But if try to secure connect  like this

> curl --include  --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" https://MY_DOMAIN/websocket

or this

> wscat -c wss://MY_DOMAIN/websocket

It returns

```
HTTP/1.1 501 Not Implemented
Server: nginx/1.19.2
Date: Tue, 09 Feb 2021 12:46:44 GMT
Content-Length: 0
Connection: keep-alive
X-flex-Cache: MISS-2
X-Powered-By: RSK Smart
```
RSK config 

```
blockchain.config.name = "main"

database.dir = /home/rsk/

rpc.providers.web.cors=MY_DOMAIN

rpc.providers.web.http.bind_address=0.0.0.0
rpc.providers.web.http.hosts.0=localhost
rpc.providers.web.http.hosts.1=MY_DOMAIN

rpc.providers.web.ws.enabled=true
rpc.providers.web.ws.port=4445
rpc.providers.web.ws.bind_address=0.0.0.0

rpc.modules = [
    { name: "eth", version: "1.0", enabled: "true" },
    { name: "net", version: "1.0", enabled: "true" },
    { name: "rpc", version: "1.0", enabled: "true" },
    { name: "web3", version: "1.0", enabled: "true" },
    { name: "evm", version: "1.0", enabled: "true" },
    { name: "sco", version: "1.0", enabled: "true" },
    { name: "txpool", version: "1.0", enabled: "true" },
    { name: "personal", version: "1.0", enabled: "true" }
]
```
**I think its configuration trouble, pls help me if possible)**

**Comment by Vovchyk** [comment]
@1doce8 looks like this issue is related to the `nginx` configuration
