### ISSUE TITLE
RPC endpoint returns "remasc" transaction that makes no sense

### ISSUE THREAD

**Issue by samsondav** [rsksmart/rskj#1484]
Hi, this is Sam from Chainlink. We've been doing some integration work with RSK and run into a bit of trouble. This command:

```curl --data '{"method":"eth_getBlockByNumber","id":"1","params":["0x30fed8", true],"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://public-node.rsk.co | jq```

returns a "REMASC" transaction with 0 gas limit, 0 gas used and 0 gas price.

This breaks ethereum compatibility because geth tools such as the client assume that the gas used is greater than 0.

It might make sense for the RPC client to not return this transaction since it does not mesh well with existing etheruem tooling and is useless from a client's perspective.

**Comment by fedejinich** [comment]
mmm I wont say that makes no sense, that transaction is part of the consensus and it might be relevant for the rsk ecosystem. Maybe we can find a middle path were both responses coexists (with gas used > 0 and without it)
