### ISSUE TITLE
RskContext not always responds to -D configuration switches

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#1500]
This is the code to reproduce the bug:
```
  public static void main (String args[]) {
        String[] rskArgs = new String[]{"-Ddatabase.dir=."};
        RskContext ctx = new RskContext(rskArgs);
    }
```

The reason may be related to compiler optimizations that remove the getRskSystemProperties() call.

Suggestion: force getRskSystemProperties() to be called on RskContext creation.

**Comment by heitorfm** [comment]
Hi, 
There are two ways to configure the database location:
1) java -cp rskj-core-2.2.0-PAPYRUS-all.jar co.rsk.Start -base-path /home/rsk/data --regtest
2) java -cp rskj-core-2.2.0-PAPYRUS-all.jar -Ddatabase.dir=/home/rsk/data co.rsk.Start --regtest

The RskContext needs to receive the arguments in that form:

```
  public static void main (String args[]) {
        String[] rskArgs = new String[]{"-base-path", "/home/rsk/data"};
        RskContext ctx = new RskContext(rskArgs);
  }
```
Like the arguments passed in the command line **after** the start class a handled to the java class.

I´ll talk to the guys to clarify it in the documentation.

Best

**Comment by aeidelman** [comment]
@heitorfm is this issue still valid?

**Comment by heitorfm** [comment]
No. Its solved.
