### ISSUE TITLE
Correct unit tests

### ISSUE THREAD

**Issue by heitorfm** [rsksmart/rskj#1566]
Correct the 3 unit tests in the maser branch

BlockProcessResultTest. buildLogMessageWithConnections
BlockProcessResultTest. buildSimpleLogMessage
FormatUtilsTest. formatNanosecondsToSeconds

![image](https://user-images.githubusercontent.com/170945/123177640-06bc1000-d45c-11eb-930e-14fa9e2d1099.png)

**Comment by aeidelman** [comment]
@heitorfm is this issue still valid?

**Comment by heitorfm** [comment]
Not any more. Thanks
