### ISSUE TITLE
From address private key could not be found in this node

### ISSUE THREAD

**Issue by jordaniac89** [rsksmart/rskj#160]
I'm trying to deploy a contract with the "eth_sendTransaction" method. I've generated keys, addresses, etc. with the GenNodeKeyId and placed them in my rsk-sample.conf per the wiki tutorial. However, when deploying the contract, all I get is "From address private key could not be found in this node". I'm attempting to deploy with Postman using the following JSON:
` {
	"jsonrpc": "2.0",
	"method": "eth_sendTransaction",
	"params": [{
		"from": <MY_ADDRESS>,
		"data": <CONTRACT_BINARY>
	}],
	"id": 1
}`
I've tried running with mining turned on and off and regenerating my keys. This is super frustrating. Any help would be appreciated.

**Comment by jordaniac89** [comment]
So, after digging through the source code for an hour or so, I found that I needed to add
`
wallet {
    accounts = [
        {
            privateKey: <MY_PRIVATE_KEY>
    ]
}
`
to the conf file. Is this correct? It looks like the contract deployed successfully after I added this.

**Comment by bcodesido** [comment]
Yes that's correct.
You where following some wiki article?

**Comment by jordaniac89** [comment]
Yes. This wiki: https://github.com/rsksmart/rskj/wiki/Compile-and-run-a-RSK-node-locally
Specifically, this page that tells you what to configure: https://github.com/rsksmart/rskj/wiki/How-to-initialize-RSK-node-configuration-file-settings.

I'm still having issues, because even after adding that and starting my node, I start the monitor app and go to "Accounts" but nothing is listed there. There's a wallet directory in my db directory (where the conf file points to) but the wallet file just has the text `MANIFEST-000004`. I can't really test my wallet to see if it can receive coins, because it looks like the rsk faucet page is broken.

**Comment by bcodesido** [comment]
When you configure your address in your node config in wallet section (as you indicate you do in the second comment) you are going to be able to operate that address throught `rpc`. I recommend you to use the [RSK Web 3 Console](https://github.com/rsksmart/rskj/wiki/RSK-Console). Using the [explorer](https://github.com/rsksmart/utilities/tree/master/explorer) (or monitoring app) your are not going to be able to operate your account.
I have tried the faucet myself and is working fine. You can check your address in the [explorer](https://explorer.rsk.co) to view your balance and transactions.

By the moment we don't have other documentation but why are working on that.
