### ISSUE TITLE
Support non-numeric values for eth_subscribe method

### ISSUE THREAD

**Issue by 7alip** [rsksmart/rskj#1626]
RSK returns "method not found" for `eth_subscribe` method if the provided id is a non-numeric character.

```shell
wscat -c wss://public-node.testnet.rsk.co/websocket
> {"jsonrpc":"2.0","id":"449b48ac-86ce-4901-ba1f-220f3b290338","method":"eth_subscribe","params":["newHeads"]}
> {"jsonrpc":"2.0","id":"449b48ac-86ce-4901-ba1f-220f3b290338","error":{"code":-32601,"message":"method not found"}}
```

This is one of the issues blocking integration with MyEtherWallet.

**Comment by Vovchyk** [comment]
@7alip, this was fixed in #1623. Closing the issue. Feel free to reopen it if you believe that this does not work as expected
