### ISSUE TITLE
TypeConverter, HexUtil are confusing

### ISSUE THREAD

**Issue by fedejinich** [rsksmart/rskj#1715]
## TypeConverter

It's deprecated and it's doing mostly the same as HexUtils. I think it should be removed it makes unnecessary noise.

## HexUtil

- What's the purpose of it? It was created after TypeConverter and it's doing practically the same thing.
- `HexUtil.leftPad()` it's a byte array manipulation, it's not related to Hex types, I think it should be moved to `ByteUtil`
- `HexUtils.toQuantityJsonHex(byte[] x)` it has no use apart from tests. What's the purpose?

I think there is a lot of space to improve this class, it needs a deeper analysis.

## My thoughts 

I think these classes are very useful but they have a lot of noise, it would be nice to make a good code cleanup.

**Comment by heitorfm** [comment]
Yes, HexUtils was the first phase of the refactoring. For better naming, placing and organization.
In the next moment we will remove the TypeConverter completely.

**Comment by heitorfm** [comment]
done
