### ISSUE TITLE
Linux package not updated 

### ISSUE THREAD

**Issue by ko0f** [rsksmart/rskj#1718]
Looking at linux package https://launchpad.net/~rsksmart/+archive/ubuntu/rskj it has an old version 3.0.1 IRIS.

This package is used to install RSKJ on Ubuntu and also by Dockerfile.Mainnet to build a docker image, as instructed by [official docs](https://developers.rsk.co/rsk/node/install/docker/) 

Need to update this so Docker users would be able to use the latest version.

**Comment by ko0f** [comment]
Workaround for Docker users -

1. Go to your Dockerfile directory
2. Download the latest JAR release `wget "https://github.com/rsksmart/rskj/releases/download/IRIS-3.2.0/rskj-core-3.2.0-IRIS-all.jar"`
3. Edit Dockerfile and add `COPY rskj-core-3.2.0-IRIS-all.jar /usr/share/rsk/rsk.jar` at the `# Supervisod CONF` section.
4. Delete old docker image if exists
5. Build

**Comment by Vovchyk** [comment]
Hi @ko0f, thanks for reporting this. We are in process of updating linux packages. I'll keep you posted.

**Comment by raucao** [comment]
The PPA is still out of date, even though this version contained a required hard fork upgrade.

**Comment by ko0f** [comment]
Fixed.

Package 3.2.0 released 9 hours ago.

**Comment by raucao** [comment]
It happened again, and again with a required hard fork version.

**Comment by Vovchyk** [comment]
@raucao, we published a “TESTNET ONLY” hard fork version (as of now, no update for mainnet is needed). Is it possible for you to use [HOP-TESTNET-4.1.1](https://hub.docker.com/layers/rsksmart/rskj/HOP-TESTNET-4.1.1/images/sha256-98eb9054bec2cfc9234f116c1b2bfc77601f394b6e2f2c1a2941590f47a81bd4) docker image in testnet?

**Comment by raucao** [comment]
We just pulled the `.jar` manually and changed the path in our systemd service for now.
