### ISSUE TITLE
Deploying with Hardhat fails with UND_ERR_SOCKET

### ISSUE THREAD

**Issue by ko0f** [rsksmart/rskj#1805]
I'm using Hardhat to deploy a smart contract and -
1. It's deployed successfully to Polygon
2. It's deployed successfully to RSK  using the public `https://public-node.rsk.co`
3. It worked in the past on my two local nodes

But when trying to deploy into RSK, it fails with - 

```bash
$ npx hardhat run scripts/deploy.js --network rsk

SocketError: closed
    at Socket.onSocketClose (./node_modules/undici/lib/client.js:967:31)
    at Socket.emit (events.js:400:28)
    at TCP.<anonymous> (net.js:675:12) {
  code: 'UND_ERR_SOCKET',
  socket: {
    localAddress: undefined,
    localPort: undefined,
    remoteAddress: undefined,
    remotePort: undefined,
    remoteFamily: undefined,
    timeout: undefined,
    bytesWritten: 209,
    bytesRead: 125
  }
}
```

One node runs RSKJ 3.2.0, the other is 3.3.0. 
Websocket works fine on my app.

Any idea what could be the reason?

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by Vovchyk** [comment]
@ko0f thanks for reporting this. Could you please share your Hardhat config file (or at least rsk network config with a full url you have in the `networks` section) ?

**Comment by ko0f** [comment]
Got ya, I was using hardhat 2.9.9 - switched to 2.9.7, will update the next time I try to deploy a contract.
