### ISSUE TITLE
Review transaction handling on block executing flow

### ISSUE THREAD

**Issue by aeidelman** [rsksmart/rskj#23]
When a block is executed (no matter it's origin) the flow starts somewhere and arrives to the BlockExecutor, then TransactionExecutor and for every transaction it runs code on the VM. 
Check Exception handling on each of the previous classes. Make special focus on go method from TransactionExecutor and play method from VM.

**Comment by tinchou** [comment]
We know there's tech debt in these classes, but they mostly don't change. We'll refactor when we need to change them.
