### ISSUE TITLE
TxTrie computed twice on Block creation

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#258]
The constructor 
public Block(byte[] parentHash, byte[] unclesHash, byte[] coinbase, byte[] logsBloom,
                 byte[] difficulty, long number, byte[] gasLimit,
                 long gasUsed, long timestamp, byte[] extraData,
                 byte[] mixHash,
                 byte[] nonce, byte[] bitcoinMergedMiningHeader, byte[] bitcoinMergedMiningMerkleProof,
                 byte[] bitcoinMergedMiningCoinbaseTransaction, byte[] receiptsRoot,
                 byte[] contractsLogRoot,
                 byte[] transactionsRoot, byte[] stateRoot,
                 List<Transaction> transactionsList, List<BlockHeader> uncleList, byte[] minimumGasPrice) {

computes:
 
this.header.setTransactionsRoot(calcTxTrie(getTransactionsList()));

But also the parent constructor called computes:
this.header.setTransactionsRoot(Block.getTxTrie(transactionsList).getHash());

The first computation is a little different because it stores the value in the txstate field, while the second does not.

Better just to move the first line to the second constructor and remove the first.

**Comment by tinchou** [comment]
I believe you are working on a stale branch. This was fixed as part of https://github.com/rsksmart/rskj/pull/229 in commit https://github.com/rsksmart/rskj/commit/c4ed31742fbe871a591006c7ca2f3b3387b9fe2c
