### ISSUE TITLE
Improve SPV proof sizes

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#265]
The TrieImpl will serialize a node according to the following code:

        public byte[] toMessage() {

        int lvalue = this.value == null ? 0 : this.value.length;
        int nnodes = this.getNumberOfChildren();
        int lshared = this.sharedPathLength;
        int lencoded = getEncodedPathLength(lshared, this.arity);

        int bits = 0;

        for (int k = 0; k < this.arity; k++) {
            byte[] nodeHash = this.getHash(k);

            if (nodeHash == null)
                continue;

            bits |= 1 << k;
        }

        ByteBuffer buffer = ByteBuffer.allocate(MESSAGE_HEADER_LENGTH + lencoded + nnodes * SHA3Helper.DEFAULT_SIZE_BYTES + lvalue);

        buffer.put((byte) this.arity);
        buffer.put((byte) (this.isSecure ? 1 : 0));
        buffer.putShort((short) bits);
        buffer.putShort((short) lshared);

        if (lshared > 0)
            buffer.put(encodedSharedPath);

        for (int k = 0; k < this.arity; k++) {
            byte[] nodeHash = this.getHash(k);

            if (nodeHash == null)
                continue;

            buffer.put(nodeHash);
        }

        if (lvalue > 0)
            buffer.put(this.value);

        return buffer.array();
    }

The value is serialized last. This means that a membership proof must specify the values of all elements in the tree branch from root to leaf. This is bad for the AccountState records, which are probably around 64 bytes in length (I must check). This may become particularity bad in the future if we allow values in the world state trie to be of arbitrary size (currently this is only true on storage tries). 
It would be much better is values would be transmitted only if needed.

The message could be serialized as:
Let nodeData =  keyencoded | nodes 

If lvalue<=32 then  return MESSAGE_HEADER_LENGTH | nodeData  | value

if lvalue >32 then return MESSAGE_HEADER_LENGTH | nodesData | valueHash

valueHash = sha3(value)

One bit (isCompressed) in the MESSAGE_HEADER would indicate which encoding is being used, so that the node hash is always serialized and constructed the same way.
 
There means that in the isCompressed case we need also to save in the store the pair (valueHash,value)

**Comment by SergioDemianLerner** [comment]
Another benefit is that is allows data deduplication.

**Comment by tinchou** [comment]
This was completed a long time ago
