### ISSUE TITLE
Prevent REMASC contract from paying less than the cost of a transaction.

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#266]
The REMASC contract distributes block rewards. However, during the early times of the platform, block rewards will be small. The resource consumption cost of updating the balances of miners and federation may be higher than the reward to distribute. Therefore I suggest not distributing any rewards if the full block reward to be paid is less than the cost of a transaccion (21K gas multiplied by the minimum gas price specified in the block header). 

Suggested changes:
````
   void processMinersFees() {
       ....
        BigInteger fullBlockReward = rewardBalance.divide(BigInteger.valueOf(remascConstants.getSyntheticSpan()));
        // ADDED psudocode
       if (fullBlockReward.isGreaterThan(GasCost.TRANSACTION*processingBlockHeader.getMinimumGasPrice()) 
         { 
            ...normal payment code...
        }
        this.removeUsedSiblings(processingBlockHeader);
    }
````

**Comment by tinchou** [comment]
This should be presented as an RSKIP if it still applies, because it would involve hard forking changes.
