### ISSUE TITLE
Test processBlockMessageUsingProcessor() depends on rlp-econded constant

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#273]
In co/rsk/net/NodeMessageHandlerTest.java:
    private static String rlp = "f9030ff902eca079431a9...000000000000000000010000088080808080c0";

There is no associated code on how to regenerate this constant. ALL constants in tests should have associated code to re-generate.
This code must be ignored every time the block format is hard-forked

**Comment by aeidelman** [comment]
Fixed in BAMBOO 0.4.0
