### ISSUE TITLE
BigInteger fields in Transaction and BlockHeader do not check maximum field sizes, not minimum representation. Some others are truncated silently.

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#302]
BlockHeader field difficulty and minimumGasPrice could be encoded with padding zeros.

Also some fields are decoded incorrectly, because only BigInteger.longValue()'s or intValue()'s are taken into consideration, but the encoded byte[] could by much larger. The result is that the number will be mis-interpreted when truncated to 8 or 4 bytes. This is the case with BlockHeader fields: number, gasLimit, gasUsed, timestamp and paidFees.

In the Transaction, none of the fields have maximum size checked, and all of them are read as arbitrary length byte arrays.

**Comment by aeidelman** [comment]
Fixed in PR #304
