### ISSUE TITLE
Bugs in SelectionRule

### ISSUE THREAD

**Issue by tinchou** [rsksmart/rskj#308]
I think both methods only check that the other block pays double the amount but don't check if they pay less than half.

@adauto82 FYI.
@donequis can provide more details if neccessary.

**Comment by adauto82** [comment]
So the bug was already in there. The correct formulation would be, "the difference between them can't be more than a factor of 2"

**Comment by tinchou** [comment]
It can, but only in one way (up), but not the other (down)

**Comment by tinchou** [comment]
@donequis looks like @adauto82 fixed this issue here, as part of #304: https://github.com/rsksmart/rskj/commit/8a97eb6

Can you verify?

**Comment by aeidelman** [comment]
Fixed in BAMBOO 0.4.0

**Comment by donequis** [comment]
I think there's an off by 1 error about this rule in #304, can this be checked?
