### ISSUE TITLE
Error while retrieving pgp public keys

### ISSUE THREAD

**Issue by quiquee** [rsksmart/rskj#322]
I am following the wiki tutorial https://github.com/rsksmart/rskj/wiki/Ensure-security-chain-of-RskJ-source-code
While retrieving the public key I receive the following error:
```

enrique@master:~/projects1/rskj$ gpg --debug-level guru --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4
gpg: enabled debug flags: packet mpi crypto filter iobuf memory cache memstat trust hashing cardio ipc clock lookup extprog
gpg: DBG: [not enabled in the source] start
gpg: DBG: chan_3 <- # Home: /home/enrique/.gnupg
gpg: DBG: chan_3 <- # Config: [none]
gpg: DBG: chan_3 <- OK Dirmngr 2.1.15 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.1.15
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KEYSERVER --clear https://secchannel.rsk.co/release.asc
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_GET -- 0x5DECF4415E3B8FA4
gpg: DBG: chan_3 <- ERR 1 General error <Unspecified source>
gpg: keyserver receive failed: General error
gpg: DBG: chan_3 -> BYE
gpg: DBG: [not enabled in the source] stop
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: secmem usage: 0/65536 bytes in 0 blocks
enrique@master:~/projects1/rskj$ 


```

**Comment by bcodesido** [comment]
As the [wiki article](https://github.com/rsksmart/rskj/wiki/Ensure-security-chain-of-RskJ-source-code#download-rsk-release-signing-key-public-key) explains:

> ... We recommend using GPG v1 to download the public key because GPG v2 has problems to connect to HTTPS key servers. ...

Make sure you are using gpg v1. To do that, run:

`$ which gpg`

The result has to be something like `/usr/bin/gpg`, then run 
`$ /usr/bin/gpg --version` 

which is going to return the gpg version. If the gpg version is 1.x to import the key run:

`/usr/bin/gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4
`
