### ISSUE TITLE
messageProcess logger service not in logback.xml

### ISSUE THREAD

**Issue by quiquee** [rsksmart/rskj#323]
The logback.xml file does not contain the messageProcessor log service, which happens to be one of the most verbose of all of them. It would be good to include it in the conf and adapt 
 as well the wiki to show it in the page: https://github.com/rsksmart/rskj/wiki/Configuring-RSK-node-logging-file-verbosity

**Comment by bcodesido** [comment]
Thanks for the report. The wiki article was updated and a [PR](https://github.com/rsksmart/rskj/pull/324) was made with this suggested change.

When the PR be merged I'm going to close this issue.

**Comment by tinchou** [comment]
@quiquee thanks for reporting! But you meant `messageProcess` in `NodeMessageHandler`, right?

**Comment by diega** [comment]
resolved in #324
