### ISSUE TITLE
Several tests use RLP encoded data which cannot be recreated

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#337]
Some examples are processBlockMessageUsingProcessor() in 
co/rsk/net/NodeMessageHandlerTest.java

Or  test_malleableSPV() in 
org/ethereum/validator/ProofOfWorkRuleTest.java
(Here is is a little worse, because the encoded data is flawed, as it has additional fields not present in our the block header)
Others: test_1(), test_2(), test_3(), test_RLP()

All blocks in  String[] blockRlps in 
co/rsk/blockchain/utils/BlockGenerator.java
Are also badly encoded.

In each test there must be a function names XXX_recreate() that recreates each constant. This is necessary for any hard fork that affects the blockheader format or transaction format.

The EventTrie merge is waiting this improvements: currently the only way to merge it is to disable some tests.

**Comment by ajlopez** [comment]
Any sample, use case, for XXX_recreate()?

The use case is not clear. Maybe there are other methods that create the blocks as you need. But I'm not sure about "recreates each constant" gas limit? difficulty? other?

**Comment by tinchou** [comment]
I think he meant that we should have the original, unserialized values, and serialize them during testing. This allows us to understand what values are being tested (compared to a raw `byte[]`).
