### ISSUE TITLE
Installed Docker for Windows, but Received Error

### ISSUE THREAD

**Issue by parkjamesh** [rsksmart/rskj#358]
Tried this command: docker run -v $(pwd):/rskj -w /rskj buildmachine:latest sh -c 'gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4 && gpg --finger 5DECF4415E3B8FA4 && gpg --verify SHA256SUMS.asc && sha256sum --check SHA256SUMS.a
sc && ./configure.sh && ./gradlew shadow reproducible'

Returned this Error Message: C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

**Comment by herrerameri** [comment]
Hi! The problem is the way that Windows manages the pwd.
You should use:

``` 
docker run -v /`pwd`:/rskj -w /rskj buildmachine:latest sh -c 'gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4 && gpg --finger 5DECF4415E3B8FA4 && gpg --verify SHA256SUMS.asc && sha256sum --check SHA256SUMS.a
sc && ./configure.sh && ./gradlew shadow reproducible'
```

**Comment by parkjamesh** [comment]
Thank you herrerameri. I should have realized Windows has its own ways and read the --help.  Your suggestion of replacing the () with '' around pwd helped, but I've encountered the next error.

**Comment by parkjamesh** [comment]
PS C:\Users\parkj_000\Docker> docker run -v /`pwd`:/rskj -w /rskj buildmachine:latest sh -c 'gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4 && gpg --finger 5DECF4415E3B8FA4 && gpg --verify SHA256SUMS.asc && sha256sum --check SHA256SUM
S.a
>> sc && ./configure.sh && ./gradlew shadow reproducible'
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 5E3B8FA4 from https server secchannel.rsk.co
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 5E3B8FA4: public key "RSK Release Signing Key <support@rsk.co>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
pub   4096R/5E3B8FA4 2017-05-16 [expires: 2022-05-15]
      Key fingerprint = 1A92 D894 2171 AFA9 51A8  5736 5DEC F441 5E3B 8FA4
uid                  RSK Release Signing Key <support@rsk.co>
sub   4096R/A44DCC86 2017-05-16 [expires: 2022-05-15]
sub   4096R/5E488E87 2017-05-16 [expires: 2022-05-15]
sub   4096R/9FC3E7C2 2017-05-16 [expires: 2022-05-15]

gpg: can't open `SHA256SUMS.asc'
gpg: verify signatures failed: file open error
sh: 2: sc: not found
PS C:\Users\parkj_000\Docker>

**Comment by parkjamesh** [comment]
I made sure the directory contained SHA256SUMS.asc, but its presence is not enough to avoid the file open error.

**Comment by parkjamesh** [comment]
gpg: can't open `SHA256SUMS.asc'
gpg: verify signatures failed: file open error
sh: 2: sc: not found
PS C:\Users\parkj_000\Docker\rskj-master> dir


    Directory: C:\Users\parkj_000\Docker\rskj-master


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/29/2017  11:10 AM                .circleci
d-----       12/29/2017  11:10 AM                gradle
d-----       12/29/2017  11:11 AM                rskj-core
-a----       12/29/2017  11:10 AM            858 .gitignore
-a----       12/29/2017  11:10 AM            908 build.gradle
-a----       12/29/2017  11:10 AM           1744 configure.sh
-a----       12/29/2017  11:10 AM          32382 COPYING
-a----       12/29/2017  11:10 AM           7613 COPYING.LESSER
-a----       12/29/2017  11:10 AM           5299 gradlew
-a----       12/29/2017  11:10 AM           2176 gradlew.bat
-a----       12/29/2017  11:10 AM           2089 README.md
-a----       12/29/2017  11:10 AM       21064350 rskj-core-0.3.0-BAMBOO-all.jar
-a----       12/29/2017  11:10 AM             47 settings.gradle
-a----       12/29/2017  11:10 AM            947 SHA256SUMS.asc


PS C:\Users\parkj_000\Docker\rskj-master>

**Comment by diega** [comment]
You must to run the `docker` command stepped into the **rskj-core** clone

**Comment by parkjamesh** [comment]
Hi Diega, I ran the docker command in rskj-clone directory but it still has a similar error message.  

PS C:\Users\parkj_000\Docker\rskj-master> cd rskj-core
PS C:\Users\parkj_000\Docker\rskj-master\rskj-core> docker run -v /`pwd`:/rskj -w /rskj buildmachine:latest sh -c 'gpg -
-keyserver https://secchannel.rsk.co/release.asc --recv-keys 5DECF4415E3B8FA4 && gpg --finger 5DECF4415E3B8FA4 && gpg --
verify SHA256SUMS.asc && sha256sum --check SHA256SUMS.asc && ./configure.sh && ./gradlew shadow reproducible'
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 5E3B8FA4 from https server secchannel.rsk.co
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 5E3B8FA4: public key "RSK Release Signing Key <support@rsk.co>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
pub   4096R/5E3B8FA4 2017-05-16 [expires: 2022-05-15]
      Key fingerprint = 1A92 D894 2171 AFA9 51A8  5736 5DEC F441 5E3B 8FA4
uid                  RSK Release Signing Key <support@rsk.co>
sub   4096R/A44DCC86 2017-05-16 [expires: 2022-05-15]
sub   4096R/5E488E87 2017-05-16 [expires: 2022-05-15]
sub   4096R/9FC3E7C2 2017-05-16 [expires: 2022-05-15]

gpg: can't open `SHA256SUMS.asc'
gpg: verify signatures failed: file open error
PS C:\Users\parkj_000\Docker\rskj-master\rskj-core>

**Comment by parkjamesh** [comment]
Question: After I build a Docker Image (which is earlier in the process) do I have to enter the Image and then docker run?  Could that be why the docker run command is not working?  If so how do I enter the freshly build Docker Image?

PS C:\Users\parkj_000\Docker> docker build -t buildmachine .
Sending build context to Docker daemon  338.9MB
Step 1/2 : FROM ubuntu:16.04
 ---> 00fd29ccc6f1
Step 2/2 : RUN apt-get update -y &&     apt-get install -y git curl gnupg-curl openjdk-8-jdk=8u151-b12-0ubuntu0.16.04.2 &&     rm -rf /var/lib/apt/lists/* &&     apt-get autoremove -y &&     apt-get clean
 ---> Using cache
 ---> fed5500310e9
Successfully built fed5500310e9
Successfully tagged buildmachine:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
PS C:\Users\parkj_000\Docker> ls

**Comment by bcodesido** [comment]
You are placed in the wrong path. You need to be placed in the repository document root.

**Comment by parkjamesh** [comment]
What is the path to the repository document root?

**Comment by parkjamesh** [comment]
PS C:\root\rskj\root> docker run -v /`pwd:/rskj -w /rskj buildmachine:latest sh -c 'gpg --keyserver https://secchannel.rsk.co/release.asc --re
cv-keys 5DECF4415E3B8FA4 && gpg --finger 5DECF4415E3B8FA4 && gpg --verify SHA256SUMS.asc && sha256sum --check SHA256SUMS.asc && ./configure.sh
 && ./gradlew shadow reproducible'
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 5E3B8FA4 from https server secchannel.rsk.co
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 5E3B8FA4: public key "RSK Release Signing Key <support@rsk.co>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
pub   4096R/5E3B8FA4 2017-05-16 [expires: 2022-05-15]
      Key fingerprint = 1A92 D894 2171 AFA9 51A8  5736 5DEC F441 5E3B 8FA4
uid                  RSK Release Signing Key <support@rsk.co>
sub   4096R/A44DCC86 2017-05-16 [expires: 2022-05-15]
sub   4096R/5E488E87 2017-05-16 [expires: 2022-05-15]
sub   4096R/9FC3E7C2 2017-05-16 [expires: 2022-05-15]

gpg: can't open `SHA256SUMS.asc'
gpg: verify signatures failed: file open error

**Comment by bcodesido** [comment]
You are placed in the wrong directory. You have to be placed in the repository document root, in your environment will be `C:\root\rskj\`.

**This is not a platform bug**, for future support please go to our (gitter channel)[https://gitter.im/rsksmart/rskj]
