### ISSUE TITLE
Review Web3 personal API importRawKey

### ISSUE THREAD

**Issue by aeidelman** [rsksmart/rskj#39]
The description of the API method is at https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_importrawkey 

Apparently, the geth node allows the immediate use of this account. In our implementation, the account is saved, but should be explicitly unlocked using unlockAccount and passphrase

**Comment by songrenkun** [comment]
where are the Keystore  or Privatekey which generated by web3.personal.newAccount("123456") saved?   thanks very much

**Comment by tinchou** [comment]
You will find them in a `wallet` store in your node database directory (by default, `$HOME/.rsk/[networkname]/`). They are encrypted and not meant to be directly manipulated.
