### ISSUE TITLE
idea import error

### ISSUE THREAD

**Issue by reymondtu** [rsksmart/rskj#405]
import source code error , order is :

1. download(RSK Bamboo Release v0.4.0)
https://github.com/rsksmart/rskj/releases
Source code (zip)

2.in idea
Import Project-> (select folder) -> Import project from external model -> Gradle 

3. build 
error message is:
Plugin with id 'witness' not found. 
Open File

in build.gradle file:
line 27:
apply plugin: 'witness'

why?

**Comment by bcodesido** [comment]
Hi,
Did you follow any of [this](https://github.com/rsksmart/rskj/wiki/Compile-and-run-a-RSK-node-locally) wiki articles?

**Comment by reymondtu** [comment]
The error in [this ](https://github.com/rsksmart/rskj/wiki/RSK-node-on-Windows) case.
but on docker case is ok.
so ,i copy (rskj-BAMBOO-0.4.0\rskj-core\libs\rsk-gradle-witness.jar) from docker case to windows
then it work!

**Comment by bcodesido** [comment]
If you follow all the steps indicated in the link of your case, there is no error. Make sure you are following all the steps including [Ensure the security chain](https://github.com/rsksmart/rskj/wiki/RSK-node-on-Windows#ensure-the-security-chain)

**Comment by reymondtu** [comment]
what's wrong i konw, because it only run on linux,macos
[Ensure security chain of RskJ source code](https://github.com/rsksmart/rskj/wiki/Ensure-security-chain-of-RskJ-source-code)
configure.sh use bash shell

you must support windows shell, such as configure.bat to build 
rskj-core/libs/rsk-gradle-witness.jar

**Comment by bcodesido** [comment]
As the instructions to [compile the node in windows](https://github.com/rsksmart/rskj/wiki/RSK-node-on-Windows#get-external-dependencies) explain, you can run configure.sh in windows git bash.
