### ISSUE TITLE
 gas limit is higher

### ISSUE THREAD

**Issue by oracle3** [rsksmart/rskj#412]
Invalid transaction f0f9044195a669dd408c7fab224f0f94889a1ec43a05a51f802975b5ac2375bf: its gas limit 6721975 is higher than the block gas limit 3002929
how to config the conf,I have always error

**Comment by herrerameri** [comment]
Hello @oracle3 ! 
Could you tell me if you are using Mainnet, Testnet o Regtest mode?

**Comment by aeidelman** [comment]
Closing due to lack of response.
