### ISSUE TITLE
can't deploy contract

### ISSUE THREAD

**Issue by oracle3** [rsksmart/rskj#417]
truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x78e82d40b68320242e75f41d46e32991d41a7328622639f0df57abbd835fa508
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:327560:30
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:64332:21
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:64331:32
    at Array.forEach (<anonymous>)
    at Object.onMessage [as callback] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:64329:22)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329703:20
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329702:12
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176186:11

**Comment by ajlopez** [comment]
The message "Network state unknown" points to have an inconsistency btw the node and the truffle internal state. Could you remove the build directory, and then, try again?

**Comment by oracle3** [comment]
I have remove the build directory and logs and node1,but error is still，can you give me a correct configuration file

**Comment by herrerameri** [comment]
Hello @oracle3 ! 
This is a sample of valid configuration to connect Truffle & RSK:

```
module.exports = {
    networks : {
        rsk: {
            from : "0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826",
            gasPrice: 1, 
            gas: 250000,
            host : "localhost",
            port : 4444,
            network_id : "*" // Match any network id
        }
    }
};
```

Some questions: 
- is your node in testnet, mainnet or regtest mode?
- is your node up to date (synced)?
- has the `from` account funds to deploy or maybe is it out of gas?

**Comment by herrerameri** [comment]
Hi @oracle3 ! Could you try it?

**Comment by HantongJI** [comment]
Hello. I have the same problem. 
Truffle v4.0.6 (core: 4.0.6)
Solidity v0.4.19 (solc-js)

truffle migrate --network rsk
Using network 'rsk'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xd32e6a36d81e0cdf1750531c1d71b0333d68afae58b482da70a4466e9276cdbe
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:112:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:128:1
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:127:1
    at Array.forEach (<anonymous>)
    at Object.onMessage [as callback] (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:125:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:259:1
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:258:10
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1

It works fine with the  regtest docker : 

var Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer) {
  deployer.deploy(Migrations, {gas: 269607});
};

And in the truffle.js
gasPrice: 1, 

but under the same conditions, errors occur with the testnet docker. I have used a valid configuration and the from account has enough fund.  It is synced (tells me false when I type in web3.eth.syncing)and then it starts switching constantly between syncing and false.

**Comment by herrerameri** [comment]
Hi @oracle3 ! Which blockNumber do you have (`web3.eth.blockNumber`)?
Please tell me blockNumber and datetime.

Thanks!

**Comment by aeidelman** [comment]
Closing due to lack of response.
