### ISSUE TITLE
Precompiled contracts don't support *returndatasize* opcode

### ISSUE THREAD

**Issue by josedahlquist** [rsksmart/rskj#420]
I was trying to use the Bridge contract methods from a contract I've created to test its functionality and noticed that I wasn't able to get the expected results using `returndatasize` and `returndatacopy`.

Here is the contract:
```
contract TestBridge{
  address bridgeAddress = 0x0000000000000000000000000000000001000006;

  function testWithCall() public returns(uint256) {
   require(bridgeAddress .call(bytes4(sha3("getMinimumLockTxValue()"))));
    assembly {
      returndatacopy(0x0, 0x0, returndatasize)
      return (0x0, returndatasize)
    }
  }
```

If you call `testWithCall` it will always return `0` (or the corresponding representation on other types).

I asked @tinchou to help me troubleshoot it and we found out that we are not using the the return data buffer as we do for regular contracts. If we modify this to mimic regular contract execution we do get the desired values.

Please let me know if you need more information about the test case.

**Comment by tinchou** [comment]
We also found we just need to assign the `contract.execute(data)` return value to `returnDataBuffer` [here](https://github.com/rsksmart/rskj/blob/c1871b7052d7ca520e1f1c657fb9ac138c7b5778/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1579) to make it work.

More testing would be necessary too to make sure precompiled contracts interact properly with Solidity. E.g. we also have the `CODESIZE` issue.

**Comment by tinchou** [comment]
Fixed in https://github.com/rsksmart/rskj/pull/636
