### ISSUE TITLE
Improvement - migration tool

### ISSUE THREAD

**Issue by herrerameri** [rsksmart/rskj#495]
I've tested the branch called `migration_tool` and I've found that if you specify a migration in which as a result you expect that one object disappears, it is present but as an empty object.

For example:
Initially, the `peer.listen` object had 1 attribute: `port`. 
Writing the following line into the `migration.properties` file:

```
peer.listen.port = peer.port
```

and running the tool, the result is similar to:

```
peer{
    port = XXXX,
    listen = {}
}
``` 

And maybe it's better if it would be:

```
peer{
    port = XXXX
}
```

Thanks!

**Comment by aeidelman** [comment]
Probably not relevant anymore, please reopen if you consider this issue still valid.
