### ISSUE TITLE
Lumino project progress

### ISSUE THREAD

**Issue by xiaofeizhu69** [rsksmart/rskj#499]
I want to know the relationship between Lumino and RSK . What's going on with Lumino?

**Comment by tinchou** [comment]
As you can see in the [Contributing Guidelines](https://github.com/rsksmart/rskj/blob/master/CONTRIBUTING.md), your question belongs to the [Telegram channel](https://t.me/Rsksmart contracts), not here.

Closing for now, but let us know if you can't find an answer!

**Comment by aeidelman** [comment]
@xiaofeizhu69 you can also ask technical questions in our [Gitter channel](https://gitter.im/rsksmart/rskj)
