### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by collheesi** [rsksmart/rskj#500]
I believe we should add a `Dockerfile` to this repository to help anyone trying to use that technology. This is a simple one:

```Dockerfile
FROM openjdk:8-jdk-alpine as builder

RUN apk add --no-cache curl git

COPY . /rskj/
WORKDIR /rskj/
RUN sh configure.sh
RUN ./gradlew shadow build -x test


FROM openjdk:8-jre
WORKDIR /rskj/
COPY --from=builder /rskj/rskj-core/build/libs/rskj-core-0.4.0-BAMBOO-all.jar .
ENTRYPOINT ["java", "-cp", "rskj-core-0.4.0-BAMBOO-all.jar", "co.rsk.Start"]
```

But we shouldn't stop there. Adding a `Dockerfile` without integrating that into our testing efforts would not be enough.

As a side note, `openjdk:8-jre-alpine` fails to run the `jar` with a `SEGFAULT` or similar.

**Comment by tinchou** [comment]
I published, for personal use, https://hub.docker.com/r/tinchou/rskj/. I don't recommend using it in production environments but could be useful for quick tests.

**Comment by diega** [comment]
I think we can move this into the _devops_ backlog (cc: @ida3m0n, @lucasvuotto )
