### ISSUE TITLE
Error in output after update to 0.4.1

### ISSUE THREAD

**Issue by ValeryDubrava** [rsksmart/rskj#519]
Client works in normal, but possible it will be helpful to research this issue:
https://gist.github.com/ValeryDubrava/2a3271b0c951b9260f090a4aab67191e

**Comment by ValeryDubrava** [comment]
It is quite frequent error in my logs.

**Comment by herrerameri** [comment]
Hello @ValeryDubrava ! 
Yes, we know this error message. 
This happens when someone is sending money to our bridge from a non Pay-to-PubkeyHash address.

Thanks to report it!
