### ISSUE TITLE
eth_getTransactionByHash returns null

### ISSUE THREAD

**Issue by ValeryDubrava** [rsksmart/rskj#520]
in version 0.4.1
`[valery@dev ~]$ curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "eth_getTransactionReceipt", "params": ["0x522a899be590988d599108945888f904d592da70eba1a910cc061a98609b3e13"] }' -H 'Content-Type: application/json' http://localhost:4444
`
`{"jsonrpc":"1.0","id":"curltest","result":{"transactionHash":"0x522a899be590988d599108945888f904d592da70eba1a910cc061a98609b3e13","transactionIndex":"0x0","blockHash":"0xc92fcef810cd99f86489f5cbae86a6e52899c130a2dbcb838c2216efe5f29cbc","blockNumber":"0x4fcfa","cumulativeGasUsed":"0x2dc6c0","gasUsed":"0x2dc6c0","contractAddress":"0xa6fee1cc99929c26e23c3c86ca19829706a417d6","logs":[],"from":"0x2f32def55ee639ddab70f4d78367d1c6ed314392","to":"0x0000000000000000000000000000000000000000","root":"0x00","status":"0x00"}}
`
`[valery@dev ~]$ curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "eth_getTransactionByHash", "params": ["0x522a899be590988d599108945888f904d592da70eba1a910cc061a98609b3e13"] }' -H 'Content-Type: application/json' http://localhost:4444
`
`{"jsonrpc":"1.0","id":"curltest","result":null}`

**Comment by emiliorizzo** [comment]
Same issue on 4.2

**Comment by tinchou** [comment]
Thanks for the update! This is merged and ready to be included in 0.4.3.

https://github.com/rsksmart/rskj/pull/528

**Comment by pdagrawal** [comment]
@tinchou I am facing this issue with ethereum RPC server. I am getting null with eth_getTransactionByHash. Please let me know what is causing this issue and how to fix this.

**Comment by tinchou** [comment]
@pdagrawal can you open a new issue and provide a repro so we can help you with your issue? This issue is for a bug that was already fixed in 0.4.3
