### ISSUE TITLE
Migration tool adds carriage return to config file lines

### ISSUE THREAD

**Issue by juli** [rsksmart/rskj#535]
The output file generated by the migration tool adds carriage return (`\r`) to every line, making it impossible to see the changes with a simple `diff` command. 
Btw the new variable names are not better than the old ones, making this migration process a depressing experience.

**Comment by diega** [comment]
Have you tried with `$ diff --strip-trailing-cr orig.conf orig.conf.new`?

**Comment by juli** [comment]
I've removed the `\r` using `tr` as I used to do 20 years ago when this things happened often and then a second issue was evident: TABS are replaced by spaces. Then we wonder why bad things happen.

https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by diega** [comment]
It's worth to mention that 20 years ago the world was a better place

**Comment by diega** [comment]
This goes beyond the scope of a simple tool for helping users to deal with the _not so frequent™_ configuration changes
