### ISSUE TITLE
Out of sync: higher block number than testnet blockchain

### ISSUE THREAD

**Issue by andresbach** [rsksmart/rskj#541]
Until last Friday I could send transactions and deploy contracts correctly but yesterday my node didn't work. For what I could see, it's out of sync (or the opposite): I have locally near 7.000 more blocks than the TestNet's blockchain. I didn't change anything in the config files or update any package since a week ago. Also, the config file is the default file from the ubuntu ppa installation + wallet enabled. The network in which the node is connected is adding ca. 5 blocks per minute.

The problem was noticed in the block 423616, in which the node tries to sync and only after 20' the block count continues rising.

**Comment by tinchou** [comment]
We've identified the issue and started preparing a new release.

Thanks for reporting, we'll keep you posted!

**Comment by herrerameri** [comment]
We've launched the new release that solves the issue.
v0.4.2: https://github.com/rsksmart/rskj/releases

Thanks for your report!
