### ISSUE TITLE
Suggest adding "Beginner" label

### ISSUE THREAD

**Issue by jrmillerwork** [rsksmart/rskj#576]
I see this used by, in particular, Roasbeef in lnd repo.

**Comment by tinchou** [comment]
Do you want that label for small issues that we think are good candidates to be contributed by beginners?

**Comment by jrmillerwork** [comment]
Yes and I guess Intermediate and Advanced labels. As mentioned, this kind of labeling seems very effective for lnd project, very hard for a beginner especially to determine what issues to begin investigating.

**Comment by diega** [comment]
We have created the [up-for-grabs](https://github.com/rsksmart/rskj/labels/up-for-grabs) label for this. We've found there are sites scraping this particular label so people eager to contribute to open source can get all projects aggregated in a single place.
About the other levels you may take a look to one of our teams labels [mining](https://github.com/rsksmart/rskj/labels/mining%20%3Apick%3A), [federation](https://github.com/rsksmart/rskj/labels/federation%20%F0%9F%92%AB) or [core](https://github.com/rsksmart/rskj/labels/core)
