### ISSUE TITLE
Increasing GAS LIMIT

### ISSUE THREAD

**Issue by y0ke** [rsksmart/rskj#76]
It seems current max gas limit is 3000000.
It's too short to deploy/run a bit complicated contract.
I assume the block size architecture is same with Ethereum's one.
sending alot of transactions to increase the block size before testing  something requires more than 3000000 gas  is the only way to go?

**Comment by aeidelman** [comment]
Thanks @y0ke, you're right about the gas limit being short. We'll be working on this soon.

**Comment by aeidelman** [comment]
@y0ke gas limit is currently 5 millon, I'll close this issue.
