### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by songrenkun** [rsksmart/rskj#770]
1.where are the Keystore  or Privatekey which generated by web3.personal.newAccount("123456") saved? 
2.how to backup wallet document? (i can't start rskj when i replace the wallet document)

3.how to get many address （address pool)?   

thanks ~

**Comment by tinchou** [comment]
The RSKj node provides a simple wallet implementation to enable testing and quick-demo scenarios. We do not provide any other functionality, and you should be using an external wallet to do any sensible development.
