### ISSUE TITLE
public-node.rsk.co is Horribly Unstable

### ISSUE THREAD

**Issue by joesixpack** [rsksmart/rskj#772]
When are you going to fix the availability problem?  It is unstable to use via MyCrypto and has been going on for a good long while.  Plenty of people trying to send transactions are fed up.  I also got a complaint from Kaspersky that the SSL certificate was self-signed and had to add an exclusion.  JSON also does not work anymore than it does on the local node:

![image](https://user-images.githubusercontent.com/23145642/53535344-51f5cc00-3ab7-11e9-8ac3-130bea575658.png)

**Comment by joesixpack** [comment]
This is highly likely your problem.  Bitch at Amazon.

![image](https://user-images.githubusercontent.com/23145642/53536947-1b22b480-3abd-11e9-9e8e-c0c7a9cd77e2.png)

**Comment by bcodesido** [comment]
Hi @joesixpack 
Thanks for reaching out. 

The SSL certificate it is not self signed, this is how you can check it:

`echo | openssl s_client -showcerts -servername public-node.rsk.co -connect public-node.rsk.co:443 2>/dev/null | openssl x509 -inform pem -noout -text`

In other hand, ICMP traffic is not allowed against our public nodes.

Regards
