### ISSUE TITLE
Can't install node

### ISSUE THREAD

**Issue by sileekon** [rsksmart/rskj#777]
I tried to install rskj node following https://github.com/rsksmart/rskj/wiki/RSK-node-on-Windows.
But I couldn't . I followed the method 'Get your RSK node-By compiling the code-for window'
And I got problems at Ensure the security chain and Compiling and running the node. 
![rsk node error01](https://user-images.githubusercontent.com/37215386/53714560-3e20e000-3e92-11e9-9227-d3faeaa2c19d.PNG)
![rsk node error02](https://user-images.githubusercontent.com/37215386/53714561-3eb97680-3e92-11e9-8137-5710afba2a0d.PNG)
I haven't use program like this.  So you may hard to help me. But please help me.

**Comment by sileekon** [comment]
The first picture is git bash error to do 'Verification of binary dependencies'
And second picture is IDEA error to run node rskj

**Comment by tinchou** [comment]
The first error tells me that there are windows line endings in your `SHA256SUMS.asc` file messing things up (see the `\r`).

@SergioDemianLerner @ajlopezrsk have any of you two seen this? You're the only two I know that are using Windows. Ping @ida3m0n in case you know something too :).

**Comment by tinchou** [comment]
I'm sorry, I forgot: this type of questions is handled in our gitter channel: https://gitter.im/rsksmart/rskj

Thanks!
