### ISSUE TITLE
JSON Parse Errors

### ISSUE THREAD

**Issue by joesixpack** [rsksmart/rskj#800]
Any ideas?

![image](https://user-images.githubusercontent.com/23145642/55489890-9fe67e00-55e7-11e9-9f5f-60c84a73d044.png)

**Comment by tinchou** [comment]
Closing as this is a support question for our Gitter channel.

But, just for the sake of completeness, your examples work for me. I would verify that cURL on Windows sends the same request as cURL on Linux and Mac (can you try that on another computer?).
