### ISSUE TITLE
Invalid `value` returned by `eth_getTransactionByHash`

### ISSUE THREAD

**Issue by alcuadrado** [rsksmart/rskj#909]
Calling `eth_getTransactionByHash` returns invalid data. The JSON-RPC spec defines that the `value` field of the returned transaction must be a `QUANTITY` value. Those have to be 0x-prefixed hex encoded strings, but RSKJ is returning a decimal string.

An example of this:

Sent `eth_getTransactionByHash` `[ '0x0c3e045afe6fb8b41369144b93a537255a2c4e8cf39fde378eb5ddfe7f82e8c9' ]`

Result: `{ hash: '0x0c3e045afe6fb8b41369144b93a537255a2c4e8cf39fde378eb5ddfe7f82e8c9',
     nonce: '0x0103',
     blockHash: null,
     blockNumber: null,
     transactionIndex: null,
     from: '0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826',
     to: null,
     gas: '0x04af1f',
     gasPrice: '0x00',
     value: '0',
     input: '0x608060405234801561001057600080fd5b5060405161047a38038061047a8339810180604052602081101561003357600080fd5b81019080805164010000000081111561004b57600080fd5b8281019050602081018481111561006157600080fd5b815185600182028301116401000000008211171561007e57600080fd5b5050929190505050806000908051906020019061009c9291906100a3565b5050610148565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100e457805160ff1916838001178555610112565b82800160010185558215610112579182015b828111156101115782518255916020019190600101906100f6565b5b50905061011f9190610123565b5090565b61014591905b80821115610141576000816000905550600101610129565b5090565b90565b610323806101576000396000f3fe608060405234801561001057600080fd5b5060043610610053576000357c010000000000000000000000000000000000000000000000000000000090048063a413686214610058578063cfae321714610113575b600080fd5b6101116004803603602081101561006e57600080fd5b810190808035906020019064010000000081111561008b57600080fd5b82018360208201111561009d57600080fd5b803590602001918460018302840111640100000000831117156100bf57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610196565b005b61011b6101b0565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561015b578082015181840152602081019050610140565b50505050905090810190601f1680156101885780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b80600090805190602001906101ac929190610252565b5050565b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102485780601f1061021d57610100808354040283529160200191610248565b820191906000526020600020905b81548152906001019060200180831161022b57829003601f168201915b5050505050905090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061029357805160ff19168380011785556102c1565b828001600101855582156102c1579182015b828111156102c05782518255916020019190600101906102a5565b5b5090506102ce91906102d2565b5090565b6102f491905b808211156102f05760008160009055506001016102d8565b5090565b9056fea165627a7a72305820247789f63d1840112d10d04bbfda9d3ceb43e44ebe9bbd6cd2154e6d1b1ae3dc0029000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000024869000000000000000000000000000000000000000000000000000000000000',
     v: '0x1b',
     r: '0x6554c25826b189fe990d63de213e148bcfbcd0eaacf50598a28cd8443f2fa0e2',
     s: '0x2308ec117772fedad389d5d6d03f529d63b59cb22035c5820d7b0258e7251937' }`

This causes problems with `ethers.js`, which fails by throwing:
```
     Error: hex string must have 0x prefix (arg="value", value="0", version=4.0.32)
      at Object.throwError (node_modules/ethers/errors.js:76:17)
      at Object.hexlify (node_modules/ethers/utils/bytes.js:165:20)
      at checkTransactionResponse (node_modules/ethers/providers/base-provider.js:201:44)
      at Function.BaseProvider.checkTransactionResponse (node_modules/ethers/providers/base-provider.js:1116:16)
      at /private/tmp/b/node_modules/ethers/providers/base-provider.js:905:47
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

I'm using `rskj-core-0.6.2-ORCHID-all.jar`

**Comment by AlanVerbner** [comment]
Ì think we are having the same issue using `web3.py`

```
05-09 13:38 default      ERROR    Unsupported type: The primitive argument must be one of: bytes,bytearray, int or bool and not str
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 328, in waitForTransactionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout, poll_latency)
  File "/usr/local/lib/python3.7/site-packages/web3/_utils/transactions.py", line 110, in wait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "/usr/local/lib/python3.7/site-packages/web3/_utils/threads.py", line 88, in sleep
    self.check()
  File "/usr/local/lib/python3.7/site-packages/web3/_utils/threads.py", line 81, in check
    raise self
```

**Comment by nicops** [comment]
The issue has already been fixed and cannot be reproduced. See

```
>>> from web3 import Web3, HTTPProvider
>>> w3 = Web3(HTTPProvider("https://public-node.rsk.co"))
>>> w3.eth.getTransaction("0x4e935981d89dd1634416ee1e761eadab6fc71c21e776519f01e4a188b0bf73b6")
AttributeDict({'hash': HexBytes('0x4e935981d89dd1634416ee1e761eadab6fc71c21e776519f01e4a188b0bf73b6'), 'nonce': 2, 'blockHash': HexBytes('0x6c4e755c5cbf736e89097d5e8c8430770cb1ffce18f9f90312417d053d0da784'), 'blockNumber': 1344641, 'transactionIndex': 0, 'from': '0x6B9939722eeD292298001cC0149C7Aa2712e3904', 'to': '0x970536A801EAcfaEB756E76990AD49b94A31eBeB', 'gas': 21000, 'gasPrice': 200000000, 'value': 10000000000000, 'input': '0x', 'v': 28, 'r': HexBytes('0xa6adeecff2814a86d293798a0243852a6c9fe44cb107039bb1bbe335dc5f1299'), 's': HexBytes('0x22cf3de4c68e3fbd9698d654e71c9fe3a6d0fdc1f51cbde6278da6f6f181b3a0')})
```
@AlanVerbner if you're still getting the error, can you share more detail into how you're making the request with web3.py ?

**Comment by AlanVerbner** [comment]
Thanks @nicops. We are going to rewrite the script so will let you know in case we find the issue again.
