### ISSUE TITLE
rsk database couldn't be moved to other directory apart from /var/lib/rsk/database/<mainnet or regtest or testnet> on Ubuntu 18.04

### ISSUE THREAD

**Issue by azamrazman** [rsksmart/rskj#952]
On Ubuntu 18.04, it was discovered that adjusting node.conf (or even, mainnet.conf), database.dir = /var/lib/rsk/database/mainnet to database.dir = "other directory" will not allow the RSK Node to start. 

Hence, if we have additional drives, for example, database.dir = /media/"username"/"HDD", RSK Node will fail to run.

**Comment by colltoaction** [comment]
Hi @azamrazman, thanks for reporting! Could you attach the log so we can take a look? We use this feature quite a lot, so I'm wondering if this could be anything related to your environment.

* do you have write access to this directory?
* does it work with another directory in the same drive?
* can you paste the exact `database.dir = ...` line?

**Comment by azamrazman** [comment]
- "do you have write access to this directory?" Answer: Yes, I changed the permission

- "does it work with another directory in the same drive?" Answer: database.dir = /home/azamrazman/Desktop does not work.

- can you paste the exact database.dir = ... line? Answer: /media/azamrazman/"HDD" and also /home/azamrazman/Desktop both does not work. 

I've attached the rsk.log file and mainnet.conf to your Gitter (for privacy reasons, I do not what to paste it here).

**Comment by azamrazman** [comment]
Managed to solve it. The trick is to change owner to "owner = rsk" for each of every directory steps. Example /media/"username"/"HDD", change the owner as:

owner = rsk for media/
owner = rsk for "username"/
owner = rsk for "HDD"/
(and so on...)

**Comment by colltoaction** [comment]
I'm glad to hear! Thanks for posting your solution!
