### ISSUE TITLE
`eth_sign` return should be fixed size

### ISSUE THREAD

**Issue by diega** [rsksmart/rskj#965]
The `ByteUtil#bigIntegerToBytes` used for encode `r` and `s` values removes the leading zero byte if present in the signed encoding, changing its final size

**Comment by raullaprida** [comment]
In Transaction.java
method getEncoded:
change
`                r = RLP.encodeElement(ByteUtil.bigIntegerToBytes(signature.getR()));
`
to
`                r = RLP.encodeElement(ByteUtil.bigIntegerToBytes(signature.getR(), 32));
`
and
`                s = RLP.encodeElement(ByteUtil.bigIntegerToBytes(signature.getS()));
`
to
`                s = RLP.encodeElement(ByteUtil.bigIntegerToBytes(signature.getS(), 32));
`

And in EthModuleWalletEnabled.java, in sign(String data, ECKey key)

Change :

` return TypeConverter.toJsonHex(ByteUtil.merge(
                ByteUtil.bigIntegerToBytes(signature.getR()),
                ByteUtil.bigIntegerToBytes(signature.getS()),
                new byte[] {signature.getV()}
        ));`

to
` return TypeConverter.toJsonHex(ByteUtil.merge(
                ByteUtil.bigIntegerToBytes(signature.getR(), 32),
                ByteUtil.bigIntegerToBytes(signature.getS(), 32),
                new byte[] {signature.getV()}
        ));`
