### ISSUE TITLE
Non-deterministic TransactionInfo retrieval

### ISSUE THREAD

**Issue by ajlopez** [rsksmart/rskj#979]
There is a method in `BlockchainImpl` that retrieves a TransactionInfo, by transaction hash
```
    public TransactionInfo getTransactionInfo(byte[] hash) {
        TransactionInfo txInfo = receiptStore.get(hash);

        if (txInfo == null) {
            return null;
        }

        Transaction tx = this.getBlockByHash(txInfo.getBlockHash()).getTransactionsList().get(txInfo.getIndex());
        txInfo.setTransaction(tx);

        return txInfo;
    }

```
Due to blockchain implementation (it processes many alternative blocks), many transaction infos could be saved for the SAME transaction, ONE per processed block that contains the transaction info. See the `ReceiptStore.get` method that retrieves only ONE TransactionInfo given the transaction hash:

```
    public TransactionInfo get(byte[] transactionHash){
        List<TransactionInfo> txs = getAll(transactionHash);

        if (txs.isEmpty()) {
            return null;
        }

        return txs.get(txs.size() - 1);
    }

````
Arbitrarly ONLY THE LAST transaction info is returned. The only real use case to call `BlockchainImpl.getTransactionInfo` is into the `LogFilter` logic, to retrieve the `TransactionInfo`. But the intention of `LogFilter` is to retrieve the `TransactionInfo` ASSOCIATED WITH A DETERMINED BLOCK. So, a wrong `TransactionInfo` could be used by log logic.

**Comment by aeidelman** [comment]
Fixed in #1605
